MyntEyeDStereoCam:
  SubTopicName:
    CamInfo: "/mynteye/left/camera_info"
    ColorImg: "/mynteye/left/image_color"
    DepthImg: "/mynteye/depth/image_raw"
    ImuData: "/mynteye/imu/data_raw_processed"
  
  PubTopicName:
    ImgImuSync: "/mynteye/synced_data"

# case 1: desktop/laptop
# case 2: jetson tx2/nano/xavier
# sensor 11: mynteye camera D1000-50 or D1000-120
# sensor 22: realsense camera R435i
CamImgLog:
  ComCase: 1
  Sensor: 11
  Info:
    Name: "left_color_img"
    Hz: "1.0"
    Type: "png"