MyntEyeDStereoCam:
  SubTopicName:
    CamInfo: "/mynteye/left/camera_info"
    ColorImg: "/mynteye/left/image_color"
    DepthImg: "/mynteye/depth/image_raw"
    ImuData: "/mynteye/imu/data_raw_processed"
  PubTopicName:
    ImgImuSync: "/mynteye/synced_data"
  SyncPolicy:
    time: 10  

RealSenseStereoCam:
  SubTopicName:
    CamInfo: "/realsense/color/camera_info"
    ColorImg: "/realsense/color/image_rect_color"
    DepthImg: "/realsense/aligned_depth_to_color/image_raw"
    GyroData: "/realsense/gyro/sample"
    AccData: "/realsense/accel/sample"
    AttData: "/imu"
  PubTopicName:
    ImuData: "/realsense/imu_data"
    ImgImuSync: "/realsense/synced_data"
    FakeUsbImg: "/usb_cam/image_raw"
  SyncPolicy:
    time: 1000

RotorsSimViCam:
  SubTopicName:
    CamInfo: "/firefly/vi_sensor/left/camera_info"
    ColorImg: "/firefly/vi_sensor/left/image_raw"
    DepthImg: "/firefly/vi_sensor/camera_depth/camera/image_raw"
    OdomData: "/firefly/odometry_sensor1/odometry"
  PubTopicName:
    ImgImuSync: "/firefly/synced_data"
  SyncPolicy:
    time: 10    

# case 1: desktop/laptop
# case 2: jetson tx2/nano/xavier
# sensor 11: mynteye camera D1000-50 or D1000-120
# sensor 22: realsense camera R435i
CamImgLog:
  ComCase: 2
  Sensor: 22
  Info:
    Name: "left_color_img"
    Hz: 0.5
    Type: "png"
